Improvement sign up sign in
WildCodeSchool/2209-wns-adleman-citycompass pull request #77
Opened 2023-05-25 15:50 UTC by JulieCombeau

2023-05-25 15:52 UTC, JulieCombeau commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Improvement_SignUp_SignIn]](https://trello.com/c/doRrVJRN/87-improvementsignupsignin)

2023-05-26 07:23 UTC, elodiedaubie requested changes
J'ai mis des commentaires dans le code

2023-05-26 07:23 UTC, elodiedaubie commented on client/src/components/FormSignUp.tsx
> +              placeholder="firstname"
Le placeholder devrait être en français

2023-05-26 07:23 UTC, elodiedaubie commented on client/src/components/FormSignUp.tsx
> +              placeholder="lastname"
le placeholder devrait être en français

2023-05-26 07:23 UTC, elodiedaubie commented on client/src/components/FormSignUp.tsx
> +              placeholder="email"
dans le place holder, je pense qu'un exemple du type monmail@mail.com serait plus pertinent en terme d'UX/UI

2023-05-26 07:23 UTC, elodiedaubie commented on client/src/components/FormSignUp.tsx
> +                    placeholder="password"
le place holder devrait être en français

2023-05-26 07:23 UTC, elodiedaubie commented on client/src/styles/modal.css
>  }
Quand on est sur le formulaire de création de compte, la modale passe en dessous du header .
De plus je pense qu'il serait plus fluide d'afficher d'abord la modale de connexion plutôt que celle de la création de compte.
![image](https://github.com/WildCodeSchool/2209-wns-adleman-citycompass/assets/80903879/52a6e7ea-f7ac-4160-be62-77c0cdd8bb8d)

2023-05-26 07:40 UTC, elodiedaubie approved these changes

2023-05-26 07:40 UTC, merged